### ISSUE TITLE
Enabling this script makes bike spin in circles

### ISSUE THREAD

**Issue by sleepingezy** [WaypointRP/wp-pocketbikes#4]
this script makes dlc and modded bikes/motorcycles. When enabled motorcycles would no longer run in straight but curved to the right.

**Comment by BackSH00TER** [comment]
@sleepingezy I don't see how this script could cause such an issue. This script is simply adding bikes as a useable item, storing metadata on the item and then spawns a bike in the world when you use the item. Nowhere in the script, does it touch anything related to handling/controls.

You likely have another script that is interfering or causing this behavior. I'm not able to reproduce this.
